# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update readme
on:
  schedule:
    - cron: '0 6,10,12,16,20,0 * * *'
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: change format hour
      run: |
        sudo timedatectl set-timezone America/Santiago
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run update
      run: |
        python main.py ${{ secrets.KEY_YOUTUBE }}
    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v5
        

